### ISSUE TITLE
데이터베이스 내 상품 로고 수정

### ISSUE THREAD

**Issue by minoflower31** [minoflower31/financial-product-recommendation-service#27]
## Description

로고 화질이 깨지는 이슈로 RDS 및 데이터베이스 내 `logo` 컬럼 수정

## Todo

- [ ] RDS에 기존 로고 삭제
- [ ] RDS에 변경할 로고 추가
- [ ] data.sql에 logo 컬럼 일부 수정
